export const TaskList = [
  {
    id: crypto.randomUUID(),
    name: "Помочь маме",
    priority: "middle",
    startDate: "2025-10-21",
    endDate: "2025-11-04",
    note: "Семья",
    status: "active",
  },
  {
    id: crypto.randomUUID(),
    name: "Изучение React",
    priority: "high",
    startDate: "2025-10-23",
    endDate: "2025-11-25",
    note: "Учеба",
    status: "active",
  },
  {
    id: crypto.randomUUID(),
    name: "Жестко накачаться айяйяй",
    priority: "low",
    startDate: "2025-07-01",
    endDate: "2025-11-25",
    note: "Спорт",
    status: "active",
  },
  {
    id: crypto.randomUUID(),
    name: "Купить молочка",
    priority: "unbelievable",
    startDate: "2025-10-22",
    endDate: "2025-11-23",
    note: "Дом",
    status: "active",
  },
  {
    id: crypto.randomUUID(),
    name: "Изменение жизни",
    priority: "middle",
    startDate: "2025-10-23",
    endDate: "2025-11-17",
    note: "Учеба",
    status: "active",
  },
];
